/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package noten;
import noten.Noten;
/**
 *
 * @author Paintdog
 */
public class NotenGUI extends javax.swing.JFrame {
    
    Noten notenapp = new noten.Noten();
    /**
     * Creates new form NotenGUI
     */
    public NotenGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_Anzeige = new javax.swing.JTextField();
        jButton_eins_plus = new javax.swing.JButton();
        jButton_eins = new javax.swing.JButton();
        jButton_eins_minus = new javax.swing.JButton();
        jButton_zwischennote = new javax.swing.JButton();
        jButton_zwei_plus = new javax.swing.JButton();
        jButton_zwei = new javax.swing.JButton();
        jButton_zwei_minus = new javax.swing.JButton();
        jButton_drei_plus = new javax.swing.JButton();
        jButton_drei = new javax.swing.JButton();
        jButton_drei_minus = new javax.swing.JButton();
        jButton_gesamtnote = new javax.swing.JButton();
        jButton_vier_minus = new javax.swing.JButton();
        jButton_vier = new javax.swing.JButton();
        jButton_vier_plus = new javax.swing.JButton();
        jButton_fuenf = new javax.swing.JButton();
        jButton_reset = new javax.swing.JButton();
        jButton_fuenf_plus = new javax.swing.JButton();
        jButton_fuenf_minus = new javax.swing.JButton();
        jButton_sechs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField_Anzeige.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jTextField_Anzeige.setText("NotenApp ist einsatzbereit.");

        jButton_eins_plus.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jButton_eins_plus.setText("1+");
        jButton_eins_plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eins_plusActionPerformed(evt);
            }
        });

        jButton_eins.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jButton_eins.setText("1");
        jButton_eins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_einsActionPerformed(evt);
            }
        });

        jButton_eins_minus.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jButton_eins_minus.setText("1-");
        jButton_eins_minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eins_minusActionPerformed(evt);
            }
        });

        jButton_zwischennote.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jButton_zwischennote.setText("<html>Teil-<br>note</html>");
        jButton_zwischennote.setPreferredSize(new java.awt.Dimension(124, 57));
        jButton_zwischennote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_zwischennoteActionPerformed(evt);
            }
        });

        jButton_zwei_plus.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jButton_zwei_plus.setText("2+");
        jButton_zwei_plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_zwei_plusActionPerformed(evt);
            }
        });

        jButton_zwei.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jButton_zwei.setText("2");
        jButton_zwei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_zweiActionPerformed(evt);
            }
        });

        jButton_zwei_minus.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jButton_zwei_minus.setText("2-");
        jButton_zwei_minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_zwei_minusActionPerformed(evt);
            }
        });

        jButton_drei_plus.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jButton_drei_plus.setText("3+");
        jButton_drei_plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_drei_plusActionPerformed(evt);
            }
        });

        jButton_drei.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jButton_drei.setText("3");
        jButton_drei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_dreiActionPerformed(evt);
            }
        });

        jButton_drei_minus.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jButton_drei_minus.setText("3-");
        jButton_drei_minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_drei_minusActionPerformed(evt);
            }
        });

        jButton_gesamtnote.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jButton_gesamtnote.setText("<html>End-<br>note</html>");
        jButton_gesamtnote.setPreferredSize(new java.awt.Dimension(124, 57));
        jButton_gesamtnote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_gesamtnoteActionPerformed(evt);
            }
        });

        jButton_vier_minus.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jButton_vier_minus.setText("4-");
        jButton_vier_minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_vier_minusActionPerformed(evt);
            }
        });

        jButton_vier.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jButton_vier.setText("4");
        jButton_vier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_vierActionPerformed(evt);
            }
        });

        jButton_vier_plus.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jButton_vier_plus.setText("4+");
        jButton_vier_plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_vier_plusActionPerformed(evt);
            }
        });

        jButton_fuenf.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jButton_fuenf.setText("5");
        jButton_fuenf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_fuenfActionPerformed(evt);
            }
        });

        jButton_reset.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jButton_reset.setText("Reset");
        jButton_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_resetActionPerformed(evt);
            }
        });

        jButton_fuenf_plus.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jButton_fuenf_plus.setText("5+");
        jButton_fuenf_plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_fuenf_plusActionPerformed(evt);
            }
        });

        jButton_fuenf_minus.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jButton_fuenf_minus.setText("5-");
        jButton_fuenf_minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_fuenf_minusActionPerformed(evt);
            }
        });

        jButton_sechs.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jButton_sechs.setText("6");
        jButton_sechs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sechsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_Anzeige)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton_eins_plus, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_eins, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_eins_minus, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton_zwei_plus, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_zwei, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_zwei_minus, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_zwischennote, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton_drei_plus, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_drei, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_drei_minus, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton_vier_plus, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_vier, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_vier_minus, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_gesamtnote, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton_fuenf_plus, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_fuenf, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_fuenf_minus, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton_sechs, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton_eins, jButton_eins_minus, jButton_eins_plus, jButton_zwischennote});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton_zwei, jButton_zwei_minus, jButton_zwei_plus});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton_drei, jButton_drei_minus, jButton_drei_plus, jButton_gesamtnote, jButton_vier, jButton_vier_minus, jButton_vier_plus});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton_fuenf, jButton_fuenf_minus, jButton_fuenf_plus, jButton_reset});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField_Anzeige, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_eins_minus, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(jButton_eins_plus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_eins, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_zwei_minus, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(jButton_zwei_plus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_zwei, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jButton_zwischennote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_drei_minus, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(jButton_drei_plus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_drei, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_vier_minus, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(jButton_vier_plus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_vier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jButton_gesamtnote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_fuenf_minus, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(jButton_fuenf_plus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_fuenf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_sechs, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton_reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton_eins, jButton_eins_minus, jButton_eins_plus});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_eins_plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eins_plusActionPerformed
        System.out.println("1+");
        notenapp.add(15);
    }//GEN-LAST:event_jButton_eins_plusActionPerformed

    private void jButton_zwei_plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_zwei_plusActionPerformed
        System.out.println("2+");
        notenapp.add(12);
    }//GEN-LAST:event_jButton_zwei_plusActionPerformed

    private void jButton_drei_plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_drei_plusActionPerformed
        System.out.println("3+");
        notenapp.add(9);
    }//GEN-LAST:event_jButton_drei_plusActionPerformed

    private void jButton_vier_plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_vier_plusActionPerformed
        System.out.println("4+");
        notenapp.add(6);
    }//GEN-LAST:event_jButton_vier_plusActionPerformed

    private void jButton_fuenf_plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_fuenf_plusActionPerformed
        System.out.println("5+");
        notenapp.add(3);
    }//GEN-LAST:event_jButton_fuenf_plusActionPerformed

    private void jButton_sechsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sechsActionPerformed
        System.out.println("6");
        notenapp.add(0);
    }//GEN-LAST:event_jButton_sechsActionPerformed

    private void jButton_einsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_einsActionPerformed
        System.out.println("1");
        notenapp.add(14);
    }//GEN-LAST:event_jButton_einsActionPerformed

    private void jButton_zweiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_zweiActionPerformed
        System.out.println("2");
        notenapp.add(11);
    }//GEN-LAST:event_jButton_zweiActionPerformed

    private void jButton_dreiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_dreiActionPerformed
        System.out.println("3");
        notenapp.add(8);
    }//GEN-LAST:event_jButton_dreiActionPerformed

    private void jButton_vierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_vierActionPerformed
        System.out.println("4");
        notenapp.add(5);
    }//GEN-LAST:event_jButton_vierActionPerformed

    private void jButton_fuenfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_fuenfActionPerformed
        System.out.println("5");
        notenapp.add(2);
    }//GEN-LAST:event_jButton_fuenfActionPerformed

    private void jButton_eins_minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eins_minusActionPerformed
        System.out.println("1-");
        notenapp.add(13);
    }//GEN-LAST:event_jButton_eins_minusActionPerformed

    private void jButton_zwei_minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_zwei_minusActionPerformed
        System.out.println("2-");
        notenapp.add(10);
    }//GEN-LAST:event_jButton_zwei_minusActionPerformed

    private void jButton_drei_minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_drei_minusActionPerformed
        System.out.println("3-");
    }//GEN-LAST:event_jButton_drei_minusActionPerformed

    private void jButton_vier_minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_vier_minusActionPerformed
        System.out.println("4-");
        notenapp.add(4);
    }//GEN-LAST:event_jButton_vier_minusActionPerformed

    private void jButton_fuenf_minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_fuenf_minusActionPerformed
        System.out.println("5-");
        notenapp.add(1);
    }//GEN-LAST:event_jButton_fuenf_minusActionPerformed

    private void jButton_zwischennoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_zwischennoteActionPerformed
        System.out.println("Bilde Teilnote...");
        double zwischennote = notenapp.bilde_zwischennote();
        jTextField_Anzeige.setText("" + zwischennote);
    }//GEN-LAST:event_jButton_zwischennoteActionPerformed

    private void jButton_gesamtnoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_gesamtnoteActionPerformed
        System.out.println("Bilde Endnote...");
        double gesamtnote = notenapp.bilde_gesamtnote();
        jTextField_Anzeige.setText("" + gesamtnote);
    }//GEN-LAST:event_jButton_gesamtnoteActionPerformed

    private void jButton_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_resetActionPerformed
        System.out.println("Reset...");
        notenapp.clear();
        jTextField_Anzeige.setText("NotenApp ist einsatzbereit.");
    }//GEN-LAST:event_jButton_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotenGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_drei;
    private javax.swing.JButton jButton_drei_minus;
    private javax.swing.JButton jButton_drei_plus;
    private javax.swing.JButton jButton_eins;
    private javax.swing.JButton jButton_eins_minus;
    private javax.swing.JButton jButton_eins_plus;
    private javax.swing.JButton jButton_fuenf;
    private javax.swing.JButton jButton_fuenf_minus;
    private javax.swing.JButton jButton_fuenf_plus;
    private javax.swing.JButton jButton_gesamtnote;
    private javax.swing.JButton jButton_reset;
    private javax.swing.JButton jButton_sechs;
    private javax.swing.JButton jButton_vier;
    private javax.swing.JButton jButton_vier_minus;
    private javax.swing.JButton jButton_vier_plus;
    private javax.swing.JButton jButton_zwei;
    private javax.swing.JButton jButton_zwei_minus;
    private javax.swing.JButton jButton_zwei_plus;
    private javax.swing.JButton jButton_zwischennote;
    private javax.swing.JTextField jTextField_Anzeige;
    // End of variables declaration//GEN-END:variables
}
