/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stackapp;

import abiturklassen.listenklassen.Stack;

/**
 *
 * @author Paintdog
 */
public class StackGUI extends javax.swing.JFrame {
    
    private Stack<String> stack = new Stack<String>();
    
    /**
     * Creates new form StackGUI
     */
    public StackGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton_isEmpty = new javax.swing.JButton();
        jButton_push = new javax.swing.JButton();
        jButton_pop = new javax.swing.JButton();
        jButton_top = new javax.swing.JButton();
        jLabel_isEmpty = new javax.swing.JLabel();
        jTextField_push = new javax.swing.JTextField();
        jLabel_pop = new javax.swing.JLabel();
        jLabel_top = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Stapel (Stack)-Anwendung");

        jButton_isEmpty.setText("isEmpty()");
        jButton_isEmpty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_isEmptyActionPerformed(evt);
            }
        });

        jButton_push.setText("push()");
        jButton_push.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_pushActionPerformed(evt);
            }
        });

        jButton_pop.setText("pop()");
        jButton_pop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_popActionPerformed(evt);
            }
        });

        jButton_top.setText("top()");
        jButton_top.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_topActionPerformed(evt);
            }
        });

        jLabel_isEmpty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel_pop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel_top.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jTextArea1.setColumns(10);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane3.setViewportView(jTextArea1);

        jTextArea2.setColumns(10);
        jTextArea2.setRows(5);
        jTextArea2.setWrapStyleWord(true);
        jScrollPane4.setViewportView(jTextArea2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_isEmpty, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_push, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel_pop, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_isEmpty, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_push)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_pop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton_isEmpty, jButton_pop, jButton_push, jButton_top});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_isEmpty, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_push)
                    .addComponent(jButton_pop)
                    .addComponent(jButton_top))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_isEmpty, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_push, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_pop)
                    .addComponent(jLabel_top))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton_isEmpty, jButton_pop, jButton_push, jButton_top});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_isEmptyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_isEmptyActionPerformed
        System.out.println(stack.isEmpty());
        if (stack.isEmpty() == true) {
            jLabel_isEmpty.setText("Ja");
        } else {
            jLabel_isEmpty.setText("Nein");
        }
    }//GEN-LAST:event_jButton_isEmptyActionPerformed

    private void jButton_popActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_popActionPerformed
        System.out.println(stack.isEmpty());
        if (stack.isEmpty() == true) {
            jLabel_pop.setText("Stapel ist leer!");
        } else {
            String value = stack.top();
            System.out.println(value);
            stack.pop();
            jLabel_pop.setText(value);
            String values = jTextArea1.getText();
            String[] liste = values.split("\n");
            String new_value = "";
            for (int i = 0; i < liste.length; i++) {
                System.out.println("Wert: " + liste[i]);
                if (i == 0) {
                    System.out.println("Wert "+ liste[i] +" ist raus!");
                } else {
                    new_value = new_value + liste[i] + "\n";
                }
            }
            System.out.println(new_value);
            jTextArea1.setText(new_value);
            jTextArea2.setText(value + "\n" + jTextArea2.getText());
        }
    }//GEN-LAST:event_jButton_popActionPerformed

    private void jButton_topActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_topActionPerformed
        System.out.println(stack.isEmpty());
        if (stack.isEmpty() == true) {
            jLabel_top.setText("Stapel ist leer!");
        } else {
            jLabel_top.setText(stack.top());
        }
    }//GEN-LAST:event_jButton_topActionPerformed

    private void jButton_pushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_pushActionPerformed
        System.out.println("Füge neues Element hinzu...");
        String new_entry = jTextField_push.getText();
        stack.push(new_entry);
        jTextArea1.setText(new_entry + "\n" + jTextArea1.getText());
        
    }//GEN-LAST:event_jButton_pushActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StackGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_isEmpty;
    private javax.swing.JButton jButton_pop;
    private javax.swing.JButton jButton_push;
    private javax.swing.JButton jButton_top;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_isEmpty;
    private javax.swing.JLabel jLabel_pop;
    private javax.swing.JLabel jLabel_top;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField_push;
    // End of variables declaration//GEN-END:variables
}
