/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bmiapp;

/**
 *
 * @author Paintdog
 */
public class BMIApp extends javax.swing.JFrame {
    
    protected double m;
    protected double l;
    protected double bmi;
    protected String status;
    
    /**
     * Creates new form BMIApp
     */
    public BMIApp() {
        initComponents();
        
        // Setze die Feedback-Felder auf ""
        jLabel_Ergebnis.setText("");
        jLabel_Status.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Körpermasse = new javax.swing.JLabel();
        jLabel_Körpergröße = new javax.swing.JLabel();
        jTextField_m = new javax.swing.JTextField();
        jTextField_l = new javax.swing.JTextField();
        jLabel_Körpermasse_Einheit = new javax.swing.JLabel();
        jLabel_Körpergröße_Einheit = new javax.swing.JLabel();
        jButton_bmi = new javax.swing.JButton();
        jButton_clear = new javax.swing.JButton();
        jLabel_Status = new javax.swing.JLabel();
        jLabel_Ergebnis = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel_Körpermasse.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel_Körpermasse.setText("Körpermasse m: ");

        jLabel_Körpergröße.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel_Körpergröße.setText("Körpergröße l:");

        jTextField_m.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField_m.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField_m.setToolTipText("Ihr Körpergewicht in kg");

        jTextField_l.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField_l.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField_l.setToolTipText("Ihre Körpergröße in m");

        jLabel_Körpermasse_Einheit.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel_Körpermasse_Einheit.setText("kg");

        jLabel_Körpergröße_Einheit.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel_Körpergröße_Einheit.setText("m");

        jButton_bmi.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton_bmi.setText("Berechnen");
        jButton_bmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_bmiActionPerformed(evt);
            }
        });

        jButton_clear.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton_clear.setText("Reset");
        jButton_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_clearActionPerformed(evt);
            }
        });

        jLabel_Status.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel_Status.setText("Ergebnis.");

        jLabel_Ergebnis.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel_Ergebnis.setText("Ergebnis.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Körpergröße)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_l)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_bmi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Körpergröße_Einheit)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel_Ergebnis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel_Körpermasse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_m, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Körpermasse_Einheit)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField_l, jTextField_m});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Körpergröße)
                    .addComponent(jTextField_l, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Körpergröße_Einheit))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Körpermasse)
                    .addComponent(jTextField_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Körpermasse_Einheit))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_bmi)
                    .addComponent(jButton_clear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel_Ergebnis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_clearActionPerformed
        jTextField_l.setText("");
        jTextField_m.setText("");
        jLabel_Ergebnis.setText("");
        jLabel_Status.setText("");
    }//GEN-LAST:event_jButton_clearActionPerformed

    private void jButton_bmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_bmiActionPerformed
        String feld_l;
        String feld_m;
        
        feld_l = jTextField_l.getText();
        feld_m = jTextField_m.getText();
        
        if (feld_l.isEmpty() || feld_m.isEmpty()) {
            jLabel_Status.setText("Bitte geben Sie Ihre Daten ein!");
            
        } else {
            l = Double.valueOf(feld_l);
            m = Double.valueOf(feld_m);
            
            bmi = m / (l * l);
            jLabel_Ergebnis.setText("Ihr BMI beträgt " + String.format("%.2f", bmi) + " kg/m².");

            if (bmi < 16) {
                status = "Sie haben starkes Untergewicht.";
            } else if (bmi < 16.9) {
                status = "Sie haben mäßiges Untergewicht.";
            } else if (bmi < 18.4) {
                status = "Sie haben leichtes Untergewicht.";
            } else if (bmi < 24.9) {
                status = "Sie haben Normalgewicht.";
            } else if (bmi < 29.9) {
                status = "Sie haben Übergewicht.";
            } else if (bmi < 34.9) {
                status = "Sie haben Adipositas Grad I.";
            } else if (bmi < 40) {
                status = "Sie haben Adipositas Grad II.";
            } else if (bmi >= 40) {
                status = "Sie haben Adipositas Grad III.";
            }
            jLabel_Status.setText(status);
        }
    }//GEN-LAST:event_jButton_bmiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BMIApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BMIApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BMIApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BMIApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BMIApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_bmi;
    private javax.swing.JButton jButton_clear;
    private javax.swing.JLabel jLabel_Ergebnis;
    private javax.swing.JLabel jLabel_Körpergröße;
    private javax.swing.JLabel jLabel_Körpergröße_Einheit;
    private javax.swing.JLabel jLabel_Körpermasse;
    private javax.swing.JLabel jLabel_Körpermasse_Einheit;
    private javax.swing.JLabel jLabel_Status;
    private javax.swing.JTextField jTextField_l;
    private javax.swing.JTextField jTextField_m;
    // End of variables declaration//GEN-END:variables
}
